package jetbrains.task.html.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SProperty;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class HtmlPage_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.append("<!DOCTYPE html>");
    tgs.newLine();
    tgs.append("<html>");
    tgs.newLine();
    tgs.increaseIndent();
    tgs.indent();
    tgs.append("<head>");
    tgs.newLine();
    ctx.getBuffer().area().increaseIndent();
    tgs.indent();
    tgs.append("<title>");
    tgs.append(SPropertyOperations.getString(ctx.getPrimaryInput(), PROPS.name$MnvL));
    tgs.append("</title>");
    tgs.newLine();
    ctx.getBuffer().area().decreaseIndent();
    tgs.indent();
    tgs.append("</head>");
    tgs.newLine();
    tgs.indent();
    tgs.append("<body>");
    tgs.newLine();
    for (SNode tag : ListSequence.fromList(SLinkOperations.getChildren(ctx.getPrimaryInput(), LINKS.content$ZFyU))) {
      tgs.indent();
      tgs.appendNode(tag);
    }
    tgs.indent();
    tgs.append("</body>");
    tgs.newLine();
    tgs.decreaseIndent();
    tgs.indent();
    tgs.append("</html>");
  }

  private static final class PROPS {
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink content$ZFyU = MetaAdapterFactory.getContainmentLink(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd2396L, 0x4318f1c33ec272b6L, "content");
  }
}
