package jetbrains.task.html.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptATag = createDescriptorForATag();
  /*package*/ final ConceptDescriptor myConceptBaseAttribute = createDescriptorForBaseAttribute();
  /*package*/ final ConceptDescriptor myConceptBaseTag = createDescriptorForBaseTag();
  /*package*/ final ConceptDescriptor myConceptClassAttribute = createDescriptorForClassAttribute();
  /*package*/ final ConceptDescriptor myConceptDivTag = createDescriptorForDivTag();
  /*package*/ final ConceptDescriptor myConceptH1 = createDescriptorForH1();
  /*package*/ final ConceptDescriptor myConceptH2 = createDescriptorForH2();
  /*package*/ final ConceptDescriptor myConceptH3 = createDescriptorForH3();
  /*package*/ final ConceptDescriptor myConceptHtmlPage = createDescriptorForHtmlPage();
  /*package*/ final ConceptDescriptor myConceptImgTag = createDescriptorForImgTag();
  /*package*/ final ConceptDescriptor myConceptOList = createDescriptorForOList();
  /*package*/ final ConceptDescriptor myConceptOListItem = createDescriptorForOListItem();
  /*package*/ final ConceptDescriptor myConceptPTag = createDescriptorForPTag();
  /*package*/ final ConceptDescriptor myConceptSpanTag = createDescriptorForSpanTag();
  /*package*/ final ConceptDescriptor myConceptTagGroup = createDescriptorForTagGroup();
  /*package*/ final ConceptDescriptor myConceptText = createDescriptorForText();
  /*package*/ final ConceptDescriptor myConceptUList = createDescriptorForUList();
  /*package*/ final ConceptDescriptor myConceptUListItem = createDescriptorForUListItem();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptATag, myConceptBaseAttribute, myConceptBaseTag, myConceptClassAttribute, myConceptDivTag, myConceptH1, myConceptH2, myConceptH3, myConceptHtmlPage, myConceptImgTag, myConceptOList, myConceptOListItem, myConceptPTag, myConceptSpanTag, myConceptTagGroup, myConceptText, myConceptUList, myConceptUListItem);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ATag:
        return myConceptATag;
      case LanguageConceptSwitch.BaseAttribute:
        return myConceptBaseAttribute;
      case LanguageConceptSwitch.BaseTag:
        return myConceptBaseTag;
      case LanguageConceptSwitch.ClassAttribute:
        return myConceptClassAttribute;
      case LanguageConceptSwitch.DivTag:
        return myConceptDivTag;
      case LanguageConceptSwitch.H1:
        return myConceptH1;
      case LanguageConceptSwitch.H2:
        return myConceptH2;
      case LanguageConceptSwitch.H3:
        return myConceptH3;
      case LanguageConceptSwitch.HtmlPage:
        return myConceptHtmlPage;
      case LanguageConceptSwitch.ImgTag:
        return myConceptImgTag;
      case LanguageConceptSwitch.OList:
        return myConceptOList;
      case LanguageConceptSwitch.OListItem:
        return myConceptOListItem;
      case LanguageConceptSwitch.PTag:
        return myConceptPTag;
      case LanguageConceptSwitch.SpanTag:
        return myConceptSpanTag;
      case LanguageConceptSwitch.TagGroup:
        return myConceptTagGroup;
      case LanguageConceptSwitch.Text:
        return myConceptText;
      case LanguageConceptSwitch.UList:
        return myConceptUList;
      case LanguageConceptSwitch.UListItem:
        return myConceptUListItem;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForATag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "ATag", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2dc30dfL);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878353277151");
    b.version(3);
    b.property("url", 0x12fdec7bd2dc3420L).type(PrimitiveTypeId.STRING).origin("1368509878353277984").done();
    b.property("content", 0x12fdec7bd30eb86aL).type(PrimitiveTypeId.STRING).origin("1368509878356588650").done();
    b.alias("link");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBaseAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "BaseAttribute", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebf41fbL);
    b.class_(false, true, false);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/4834880020855865851");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForBaseTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "BaseTag", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.class_(false, true, false);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/4834880020855736317");
    b.version(3);
    b.property("class", 0x12fdec7bd2e5654cL).type(PrimitiveTypeId.STRING).origin("1368509878353880396").done();
    b.property("style", 0x12fdec7bd2e567c6L).type(PrimitiveTypeId.STRING).origin("1368509878353881030").done();
    b.property("id", 0x12fdec7bd2e96c2dL).type(PrimitiveTypeId.STRING).origin("1368509878354144301").done();
    b.aggregate("InnerTags", 0x4318f1c33ebdd3f8L).target(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd91bbL).optional(false).ordered(true).multiple(false).origin("4834880020855772152").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClassAttribute() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "ClassAttribute", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebf499fL);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseAttribute
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebf41fbL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/4834880020855867807");
    b.version(3);
    b.alias("class");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForDivTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "DivTag", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2f9b360L);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878355211104");
    b.version(3);
    b.alias("div");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForH1() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "H1", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2e52314L);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878353863444");
    b.version(3);
    b.property("content", 0x12fdec7bd2e529c9L).type(PrimitiveTypeId.STRING).origin("1368509878353865161").done();
    b.alias("# ");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForH2() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "H2", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2f57bbcL);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878354934716");
    b.version(3);
    b.property("content", 0x12fdec7bd2f587a5L).type(PrimitiveTypeId.STRING).origin("1368509878354937765").done();
    b.alias("## ");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForH3() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "H3", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2f7ace2L);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878355078370");
    b.version(3);
    b.property("content", 0x12fdec7bd2f7ace3L).type(PrimitiveTypeId.STRING).origin("1368509878355078371").done();
    b.alias("### ");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForHtmlPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "HtmlPage", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd2396L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/4834880020855726998");
    b.version(3);
    b.aggregate("content", 0x4318f1c33ec272b6L).target(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL).optional(true).ordered(true).multiple(true).origin("4834880020856074934").done();
    b.alias("html");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForImgTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "ImgTag", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd301fcccL);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878355754188");
    b.version(3);
    b.property("src", 0x12fdec7bd30208e4L).type(PrimitiveTypeId.STRING).origin("1368509878355757284").done();
    b.property("alt", 0x12fdec7bd3020cdcL).type(PrimitiveTypeId.STRING).origin("1368509878355758300").done();
    b.alias("img");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "OList", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2e3ebd0L);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878353783760");
    b.version(3);
    b.aggregate("items", 0x12fdec7bd2e40e69L).target(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2e3ef45L).optional(false).ordered(true).multiple(true).origin("1368509878353792617").done();
    b.alias("oredered list");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOListItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "OListItem", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2e3ef45L);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878353784645");
    b.version(3);
    b.property("content", 0x12fdec7bd2e3f33cL).type(PrimitiveTypeId.STRING).origin("1368509878353785660").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "PTag", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebdc9cfL);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/4834880020855769551");
    b.version(3);
    b.alias("paragraph");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSpanTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "SpanTag", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2fe5de2L);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878355516898");
    b.version(3);
    b.alias("span");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTagGroup() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "TagGroup", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd91bbL);
    b.class_(false, false, false);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/4834880020855755195");
    b.version(3);
    b.aggregate("tags", 0x4318f1c33ebd94aeL).target(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL).optional(true).ordered(true).multiple(true).origin("4834880020855755950").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "Text", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ec17bbdL);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/4834880020856011709");
    b.version(3);
    b.property("text", 0x4318f1c33ec181d6L).type(PrimitiveTypeId.STRING).origin("4834880020856013270").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUList() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "UList", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2de83a7L);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878353429415");
    b.version(3);
    b.aggregate("items", 0x12fdec7bd2de9040L).target(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2dddcaeL).optional(false).ordered(true).multiple(true).origin("1368509878353432640").done();
    b.alias("unordered list");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForUListItem() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("jetbrains.task.html", "UListItem", 0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x12fdec7bd2dddcaeL);
    b.class_(false, false, false);
    // extends: jetbrains.task.html.structure.BaseTag
    b.super_(0xe3ef414942a74e42L, 0x8bc2f96cb576bf56L, 0x4318f1c33ebd47fdL);
    b.origin("r:731e320f-bed6-419a-8b89-89879bbf0312(jetbrains.task.html.structure)/1368509878353386670");
    b.version(3);
    b.property("content", 0x12fdec7bd2e0824fL).type(PrimitiveTypeId.STRING).origin("1368509878353560143").done();
    b.alias("* ");
    return b.create();
  }
}
